### ISSUE TITLE
multi-class expert-assisted 

### ISSUE THREAD

**Issue by shaker402** [vladan-stojnic/ML-based-WAF#1]
you perform multi-class information retrieval by calculated Features based TFIDF on characters  so i need to use  

multi-class expert-assisted   so this   approach, the tokenization was performed using the features defined by the expert (see Table I).  . in this case does not  need to apply the  TFIDF  schema  
![image](https://user-images.githubusercontent.com/49626160/138540725-ed5cf9d0-deec-4263-99df-e7fb24ae1849.png)

so can you help us to compare between two approah   by adding code for this reason pleas

**Comment by vladan-stojnic** [comment]
I am not sure which code you want me to add. The code I used, with TF-IDF features, is given in the [ThreatPrediction notebook](https://github.com/vladan-stojnic/ML-based-WAF/blob/master/Classifier/TheratPrediction.ipynbl) and you can implement other needed approaches.
