### ISSUE TITLE
sniffing.py

### ISSUE THREAD

**Issue by Mohamed1Ashour** [vladan-stojnic/ML-based-WAF#3]
![image](https://user-images.githubusercontent.com/116355816/205338921-8a0ee7d3-b69b-43d1-98b4-78ca5ea81b17.png)
![image](https://user-images.githubusercontent.com/116355816/205339005-5d33a847-1894-4a52-9d10-142e51990d2c.png)
i can't understand this lines in the code..can you help me to understand this lines of code?

**Comment by AbdelrahmanMohamed-Netro** [comment]
+1

**Comment by vladan-stojnic** [comment]
Hi,

Those lines are part of configuring [scapy](https://scapy.net) library that is used intercept and sniff network packets. You can find explanation of those in the official documentation of scapy. For bind_layers it is given [here](https://scapy.readthedocs.io/en/latest/build_dissect.html#binding-layers), and for sniff they are [here](https://scapy.readthedocs.io/en/latest/api/scapy.sendrecv.html#scapy.sendrecv.sniff).
